name: shapesider
recipe: lemp
config:
  via: nginx
  config:
    vhosts: .lando/nginx.conf
  php: "8.4"
  webroot: public
  services:
    mariadb:
      type: mariadb:11.5
    phpmyadmin:
      type: phpmyadmin
    appserver:
      overrides:
        volumes:
          - ./storage:/app/public/storage
