name: shapesider
recipe: lemp
config:
  via: nginx
  config:
    vhosts: .lando/nginx.conf
  php: "8.2"
  webroot: public
  services:
    mariadb:
      type: mariadb
    phpmyadmin:
      type: phpmyadmin
